apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecost-2.4.3-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    upgrade:
      toV2: false # TODO: Handle upgrades.

    kubecostFrontend:
      enabled: true
      # TODO(takirala): publish new image and consume it
      # fullImageName: ghcr.io/mesosphere/dkp-container-images/gcr.io/kubecost1/frontend:prod-1.106.7-d2iq.1
      deployMethod: singlepod # Other possible value is `haMode` that is supported only with enterprise license.
    priority:
      enabled: true
      name: dkp-high-priority

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: kommander-traefik
        ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "${workspaceNamespace}-stripprefixes@kubernetescrd,${workspaceNamespace}-forwardauth@kubernetescrd"
      paths:
        - "/dkp/kubecost/frontend/"
      hosts:
        - ""
      tls: []

    prometheus:
      server:
        priorityClassName: dkp-high-priority
      configmapReload:
        prometheus:
          enabled: true
          #image:
            #repository: ghcr.io/jimmidyson/configmap-reload
            #tag: v0.14.0
        alertmanager:
          enabled: true
          #image:
            #repository: ghcr.io/jimmidyson/configmap-reload
            #tag: v0.14.0
    grafana:
      priorityClassName: dkp-high-priority
      image:
        repository: ghcr.io/mesosphere/dkp-container-images/docker.io/grafana/grafana
        tag: 10.3.3-d2iq.0
      grafana.ini:
        log:
          level: warn
        server:
          protocol: http
          enable_gzip: true
          root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
          serve_from_sub_path: false # Set to false on Grafana v10+
        auth.proxy:
          enabled: true
          header_name: X-Forwarded-User
          auto-sign-up: true
        auth.basic:
          enabled: false
        users:
          auto_assign_org_role: Admin
        analytics:
          reporting_enabled: false
          check_for_updates: false

    kubecostProductConfigs:
      # used for display in Kubecost UI
      clusterName: "Kommander Managed Cluster"
