apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    nfd:
      enabled: false
      deployNodeFeatureRules: true
    upgradeCRDs: true
    sriovNetworkOperator:
      enabled: false
    maintenanceOperator:
      enabled: false
    sriov-network-operator:
      images:ghcr.io/k8snetworkplumbingwg/network-resources-injector
        resourcesInjector: :v1.8.0
