---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-${appVersion}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "oci://ghcr.io/mesosphere/charts/kubefed"
  ref:
    tag: 0.11.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubefed
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-${appVersion}-chart
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    serverSideApply: false
    crds: CreateReplace
    remediation:
      retries: 30
  targetNamespace: kube-federation-system
  upgrade:
    disableTakeOwnership: true # This is needed cuz kubefed controller-manager races with helm-controller for ownership of a KubefedConfig resource created from helm chart.
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: kubefed
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-${appVersion}-config-defaults
    - kind: ConfigMap
      name: kubefed-overrides
      optional: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ValidatingWebhookConfiguration
              name: validations.core.kubefed.io
            patch: |
              apiVersion: admissionregistration.k8s.io/v1
              kind: ValidatingWebhookConfiguration
              metadata:
                name: validations.core.kubefed.io
              webhooks:
                - name: federatedtypeconfigs.core.kubefed.io
                  failurePolicy: Ignore
                - name: kubefedclusters.core.kubefed.io
                  failurePolicy: Ignore
                - name: kubefedconfigs.core.kubefed.io
                  failurePolicy: Ignore
          - target:
              kind: MutatingWebhookConfiguration
              name: mutation.core.kubefed.io
            patch: |
              apiVersion: admissionregistration.k8s.io/v1
              kind: MutatingWebhookConfiguration
              metadata:
                name: mutation.core.kubefed.io
              webhooks:
                - name: kubefedconfigs.core.kubefed.io
                  failurePolicy: Ignore
