---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-${appVersion}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "oci://ghcr.io/mesosphere/charts/kommander-ui"
  ref:
    tag: 17.234.13
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kommander-ui
  namespace: ${releaseNamespace}
spec:
  dependsOn:
    - namespace: ${releaseNamespace}
      name: kommander
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-${appVersion}-chart
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    serverSideApply: true
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    serverSideApply: enabled
    crds: CreateReplace
    remediation:
      retries: 30
  rollback:
    serverSideApply: enabled
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-${appVersion}-config-defaults
    - kind: ConfigMap
      name: kommander-ui-overrides
      optional: true
  targetNamespace: ${releaseNamespace}
