apiVersion: v1
kind: ConfigMap
metadata:
  name: centralized-kubecost-2.4.3-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    global:
      prometheus:
        enabled: false
        fqdn: http://kubecost-prometheus-server.kommander.svc.cluster.local

      grafana:
        enabled: false
        # Use kommander monitoring Grafana instance
        domainName: centralized-grafana.${releaseNamespace}.svc.cluster.local

    kubecostFrontend:
      enabled: true # TODO(takirala): Should we disable it because it will be unusable without license?
      # TODO(takirala): publish new image and consume it
      # fullImageName: ghcr.io/mesosphere/dkp-container-images/gcr.io/kubecost1/frontend:prod-1.106.7-d2iq.1
      deployMethod: singlepod # Other possible value is `haMode` that is supported only with enterprise license.
    priority:
      enabled: true
      name: dkp-high-priority

    # TODO(takirala): disable it if we disable frontend as well.
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: kommander-traefik
        ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "${releaseNamespace}-stripprefixes@kubernetescrd,${releaseNamespace}-forwardauth@kubernetescrd"
      paths:
        - "/dkp/kommander/kubecost/frontend/"
      hosts:
        - ""
      tls: []

    kubecostDeployment:
      labels:
        vendor.kubecost.io/partner: d2iq

    podSecurityPolicy:
      enabled: false

    grafana:
      # These values are set so that kubecost grafana dashboards are installed.
      # Grafana itself is not installed.
      sidecar:
        image:
          repository: docker.io/kiwigrid/k8s-sidecar
          tag: 1.28.0
        dashboards:
          enabled: true
          label: grafana_dashboard_kommander
        datasources:
          enabled: true
          defaultDatasourceEnabled: false
          label: grafana_datasource_kommander

    prometheus:
      fullnameOverride: "kommander-kubecost-prometheus"
      server:
        fullnameOverride: "kommander-kubecost-prometheus-server"
        priorityClassName: dkp-high-priority
      alertmanager:
        fullnameOverride: "kommander-kubecost-prometheus-alertmanager"
        priorityClassName: dkp-high-priority
      kube-state-metrics:
        fullnameOverride: "kommander-kubecost-prometheus-kube-state-metrics"
        priorityClassName: dkp-high-priority

    kubecostProductConfigs:
      grafanaURL: "/dkp/kommander/monitoring/grafana"
      # used for display in Kubecost UI
      clusterName: "Kommander Host"
