# Copy grafana-datasource cm after it has been created in the release.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecost-cosi-secret-create
  namespace: kubecost
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubecost-cosi-secret-create
rules:
  - apiGroups: ["v1"]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubecost-cosi-secret-create
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubecost-cosi-secret-create
subjects:
  - kind: ServiceAccount
    name: kubecost-cosi-secret-create
    namespace: kubecost
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubecost-cosi-secret-create
  namespace: kubecost
spec:
  template:
    metadata:
      name: kubecost-cosi-secret-create
    spec:
      serviceAccountName: kubecost-cosi-secret-create
      restartPolicy: OnFailure
      priorityClassName: dkp-high-priority
      containers:
        - name: kubectl
          image: "${kubetoolsImageRepository:=bitnami/kubectl}:${kubetoolsImageTag:=1.30.5}"
          command:
            - sh
            - -c
            - |
              # Skip this job if a secret already exists.
              if kubectl get secret -n kubecost federated-store; then
                  echo "Secret federated-store already exists. Skipping the job."
                  exit 0
              fi
              # Skip this job if the COSI bucket secret does not exist.
              # TODO(takirala): Do we need to wait for HelmRelease? Probably not, but make sure.
              if ! kubectl get secret -n kubecost dkp-kubecost-cosi-storage; then
                  echo "COSI bucket secret does not exist. Skipping the job."
                  exit 0
              fi
              # TODO(takirala): Use the cosi secret instead of ceph raw secret
              access_key=$(kubectl get secret -n kubecost dkp-kubecost-cosi-storage -o go-template='{{ .data.AWS_ACCESS_KEY_ID | base64decode }}')
              secret_key=$(kubectl get secret -n kubecost dkp-kubecost-cosi-storage -o go-template='{{ .data.AWS_SECRET_ACCESS_KEY | base64decode }}')
              # Create a file named federated-store.yaml
              cat <<EOF > federated-store.yaml
              type: S3
              config:
                bucket: "dkp-kubecost-cosi-storage"
                endpoint: "rook-ceph-rgw-dkp-object-store.kommander.svc"
                region: ""
                access_key: "${access_key}"
                secret_key: "${secret_key}"
                insecure: true # TODO(takirala): flip this boolean
                signature_version2: false
                put_user_metadata:
                  "X-Amz-Acl": "bucket-owner-full-control"
                http_config:
                  idle_conn_timeout: 90s
                  response_header_timeout: 2m
                  insecure_skip_verify: true # TODO(takirala): flip this boolean
                trace:
                  enable: false # Enable to debug errors (if any)
                part_size: 134217728
              EOF
