apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    postgresql:
      priorityClassName: "dkp-critical-priority"
    auth:
      enabled: true
    image:
      rag:
        repository: "docker.io/mesosphere/ai-navigator-rag"
      tag: "0.8.0-dev.2"
