---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    # values.yaml content to enable only Gateway API CRDs installation
    gatewayAPI: true
    traefik: false
    hub: false
    deleteOnUninstall: false
---
# now the cert-manager k-app's HelmRelease has an optional valuesFrom pointing to this ConfigMap
# once this k-app is ready, the cert-manager HelmRelease eventually reconciles to pick up this ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-gateway-api-crds-${releaseNamespace}-overrides
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
