---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    # values.yaml content to enable only Gateway API CRDs installation
    gatewayAPI: true
    traefik: false
    hub: false
    deleteOnUninstall: false
---
# this is needed to support NAI
# https://jira.nutanix.com/browse/NCN-112584
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-gateway-api-crds-${releaseNamespace}-overrides
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
