---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-${appVersion}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "oci://docker.io/mesosphere/kommander-appmanagement-chart"
  ref:
    tag: "${kommanderChartVersion:=v2.18.0-dev.28}"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kommander-appmanagement
  namespace: ${releaseNamespace}
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-${appVersion}-chart
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    serverSideApply: true
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    serverSideApply: enabled
    crds: CreateReplace
    remediation:
      retries: 30
  rollback:
    serverSideApply: enabled
  releaseName: kommander-appmanagement
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-${appVersion}-config-defaults
    - kind: ConfigMap
      name: kommander-appmanagement-overrides
      optional: true
