apiVersion: v1
kind: ConfigMap
metadata:
  name: centralized-kubecost-2.5.0-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    global:
      prometheus:
        enabled: false
        fqdn: http://kubecost-prometheus-server.kommander.svc.cluster.local

      savedReports:
        # Refer https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/reports to create reports
        enabled: false

      grafana:
        enabled: false
        # Use kommander monitoring Grafana instance
        domainName: centralized-grafana.${releaseNamespace}.svc.cluster.local

      notifications:
        alertmanager:
          # If true, allow kubecost to write to alertmanager
          enabled: true
          fqdn: http://kubecost-prometheus-alertmanager.kommander.svc.cluster.local

    kubecostModel:
      federatedStorageConfigSecret: "federated-store" # Secret should have a key named "federated-store.yaml" with the federated storage credentials

    kubecostAggregator:
      # deployMethod determines how Aggregator is deployed. Current options are
      # "singlepod" (within cost-analyzer Pod) "statefulset" (separate
      # StatefulSet), and "disabled".
      deployMethod: statefulset
      persistentConfigsStorage:
        storageClass: ""  # default storage class
        storageRequest: 1Gi
      aggregatorDbStorage:
        storageClass: ""  # default storage class
        storageRequest: 128Gi
      cloudCost:
        # The cloudCost component of Aggregator depends on
        # kubecostAggregator.deployMethod:
        # kA.dM = "singlepod" -> cloudCost is run as container inside cost-analyzer
        # kA.dM = "statefulset" -> cloudCost is run as single-replica Deployment
        enabled: false
      # Log level for the aggregator container. Options are "trace", "debug", "info", "warn", "error", "fatal", "panic"
      logLevel: info
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
      jaeger:
        # Enable this to use jaeger for tracing, useful for debugging
        enabled: false
        image: jaegertracing/all-in-one
        imageVersion: 1.64.0 # Pin the image here to avoid pulling in latest as that would affect CVE scans

    federatedETL:
      # Centralized kubecost should not write data to s3 storage. It's read-only.
      federatedCluster: false

    kubecostFrontend:
      enabled: true
      fullImageName: gcr.io/kubecost1/frontend:prod-2.5.0
      deployMethod: singlepod # Other possible value is `haMode` that is supported only with enterprise license.
      ipv6:
        enabled: false

    priority:
      enabled: true
      name: dkp-high-priority

    forecasting:
      # Enable this to use kubecost's cost forecosting model
      enabled: false

    # Define persistence volume for cost-analyzer, more information at https://github.com/kubecost/docs/blob/master/storage.md
    persistentVolume:
      # Upgrades from original default 0.2Gi may break if automatic disk resize is not supported
      # https://github.com/kubecost/cost-analyzer-helm-chart/issues/507
      size: 32Gi
      # Note that setting this to false means configurations will be wiped out on pod restart.
      enabled: true
      # storageClass: "-"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: kommander-traefik
        ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: "${releaseNamespace}-stripprefixes@kubernetescrd,${releaseNamespace}-forwardauth@kubernetescrd"
      paths:
        - "/dkp/kommander/kubecost/frontend/"
      hosts:
        - ""
      tls: []

    prometheus:
      server:
        fullnameOverride: "kubecost-prometheus-server"
        # If clusterIDConfigmap is defined, instead use user-generated configmap with key CLUSTER_ID
        # to use as unique cluster ID in kubecost cost-analyzer deployment.
        # This overrides the cluster_id set in prometheus.server.global.external_labels.
        # NOTE: This does not affect the external_labels set in prometheus config.
        clusterIDConfigmap: kubecost-cluster-info-configmap
        global:
          external_labels:
            cluster_id: $CLUSTER_ID

    grafana:
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard_kommander
        datasources:
          enabled: true
          defaultDatasourceEnabled: false
          label: grafana_datasource_kommander

    kubecostProductConfigs:
      grafanaURL: "/dkp/kommander/monitoring/grafana"
      clusterName: ""
      clusterProfile: production
      cloudIntegrationSecret: ""
      productKey:
        enabled: false
        #key: YOUR_KEY

    # COSI related resources
    bucketClasses: # Cluster scoped resource
    - name: kubecost-cosi-storage
      driverName: rook-ceph.ceph.objectstorage.k8s.io
      deletionPolicy: Delete
      parameters:
        objectStoreUserSecretName: rook-ceph-object-user-dkp-object-store-cosi-admin
        objectStoreUserSecretNamespace: kommander
    bucketAccessClasses: # Cluster scoped resource
    - name: kubecost-cosi-storage
      driverName: rook-ceph.ceph.objectstorage.k8s.io
      authenticationType: KEY
      parameters:
        # This secret (backed by a ceph user) is created below in the driver config.
        objectStoreUserSecretName: rook-ceph-object-user-dkp-object-store-cosi-admin
        objectStoreUserSecretNamespace: kommander
    bucketClaims: # Namespace scoped resource
    - name: kubecost-cosi-storage
      namespace: kubecost
      bucketClassName: kubecost-cosi-storage
      protocols:
        - s3
    bucketAccesses: # Namespace scoped resource
    - name: kubecost-cosi-storage
      namespace: kubecost
      bucketAccessClassName: kubecost-cosi-storage
      bucketClaimName: kubecost-cosi-storage
      protocol: s3
      credentialsSecretName: federated-store
    cosiProviders:
      ceph:
        driver:
          enabled: true
          name: ceph-cosi-driver
          namespace: kommander
          spec:
            deploymentStrategy: Auto
        adminuser:
          enabled: true
          name: cosi-admin
          namespace: kommander
          spec:
            displayName: "ceph cosi admin"
            store: dkp-object-store # name of the CephObjectStore
            capabilities:
              bucket: "*"
              user: "*"
