apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    priorityClassName: dkp-high-priority
    image:
      registry: pullthrough.infra.nkp.sh
      repository: mesosphere/nkp-mcp
      pullPolicy: IfNotPresent
    server:
      enableImpersonation: true
      enableFieldFiltering: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
