apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    # Default values for AMD Network Operator (rocm-network/network-operator-charts).
    # See https://github.com/ROCm/network-operator for full options.
