{
 "title": "Platform Apps / Velero",
 "tags": [
  "velero",
  "platform apps"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "schedule",
    "label": "Schedule",
    "query": {
     "query": "label_values(velero_backup_success_total, schedule)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_success_total{schedule=~\"$schedule\"} / velero_backup_attempt_total{schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Number of Successful Backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_success_total{schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Number of Failed Backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_failure_total{schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Restore Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_restore_success_total{schedule=~\"$schedule\"} / velero_restore_attempt_total{schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Number of Successful Restores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_restore_success_total{schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Number of Failed Restores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_restore_failed_total{schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Last Successful Backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule=~\"$schedule\"}) / 60 / 60"
    }
   ]
  },
  {
   "title": "Avg Backup Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(velero_backup_duration_seconds_sum{schedule=~\"$schedule\"} / velero_backup_duration_seconds_count{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Backup Duration: 90th Percentile ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\"}[5m]))",
     "legendFormat": "{{`{{schedule}}`}}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "velero_backup_tarball_size_bytes{schedule=~\"$schedule\"}",
     "legendFormat": "{{`{{schedule}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"velero-kubeaddons\"}",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  },
  {
   "title": "GC rate / 2m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{service=~\"velero-kubeaddons\"}[2m])) by (service)",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  }
 ]
}