---
# TODO: delete after merging the cosi-bucket-kit chart
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: takirala
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: https://takirala.github.io/charts/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubecost-cosi-storage
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: cosi-bucket-kit
      sourceRef:
        kind: HelmRepository
        name: takirala
        #name: mesosphere.github.io-charts-stable
        namespace: kommander-flux
      version: 0.0.1-alpha.0
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: kubecost-cosi-storage
  targetNamespace: ${releaseNamespace}
  valuesFrom:
    - kind: ConfigMap
      name: centralized-kubecost-2.5.0-d2iq-defaults
    - kind: ConfigMap
      name: centralized-kubecost-overrides
      optional: true
---
