{
 "title": "Core Components / Calico",
 "tags": [
  "calico",
  "core components"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hosts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(felix_host)" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99,sum(irate(process_cpu_seconds_total{job=\"kubernetes-calico-node\"}[5m])))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg (container_memory_working_set_bytes{pod_name=~\"calico-node-.*\", namespace=\"kube-system\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Exec Time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(felix_exec_time_micros{quantile=\"0.99\"}[5m])",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Active IP Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_ipsets_calico", "legendFormat": "{{`{{instance}}`}}" }
   ]
  },
  {
   "title": "Active Local Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_endpoints", "legendFormat": "{{`{{instance}}`}}" }
   ]
  },
  {
   "title": "Active Local Policies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_policies", "legendFormat": "{{`{{instance}}`}}" }
   ]
  },
  {
   "title": "Active Local Selectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_selectors", "legendFormat": "{{`{{instance}}`}}" }
   ]
  },
  {
   "title": "Active Local Tags",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_active_local_tags", "legendFormat": "{{`{{instance}}`}}" }
   ]
  },
  {
   "title": "Cluster Host Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_host_endpoints",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Cluster Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_cluster_num_hosts", "legendFormat": "{{`{{instance}}`}}" }
   ]
  },
  {
   "title": "Cluster Workload Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_workload_endpoints",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Update Apply Duration p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_apply_time_seconds{quantile=\"0.99\"}[5m])",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Update Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_int_dataplane_failures[5m]))",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Message Types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_int_dataplane_messages[5m])) by (type)",
     "legendFormat": "{{`{{type}}`}}"
    }
   ]
  },
  {
   "title": "Message Batch Sizes p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_msg_batch_size{quantile=\"0.99\"}[5m])",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  { "title": "iptables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Active Chains",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(felix_iptables_chains) by (table)",
     "legendFormat": "{{`{{table}}`}}"
    }
   ]
  },
  {
   "title": "Active Rules",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(felix_iptables_rules) by (table)",
     "legendFormat": "{{`{{table}}`}}"
    }
   ]
  },
  {
   "title": "Lines Executed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (increase(felix_iptables_lines_executed[5m]))",
     "legendFormat": "{{`{{table}}`}}"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_save_calls[5m]))",
     "legendFormat": "Save"
    },
    {
     "expr": "sum(rate(felix_iptables_restore_calls[5m]))",
     "legendFormat": "Restore"
    }
   ]
  },
  {
   "title": "Save Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_iptables_save_errors[5m])) by (instance)",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Restore Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_iptables_restore_errors[5m])) by (instance)",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  }
 ]
}