apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nkp-insights
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-${appVersion}
    namespace: ${releaseNamespace}
  install:
    serverSideApply: true
    remediation:
      retries: 30
  interval: 15s
  releaseName: nkp-insights
  targetNamespace: ${releaseNamespace}
  timeout: 10m
  upgrade:
    serverSideApply: enabled
    remediation:
      retries: 30
      strategy: uninstall
  rollback:
    serverSideApply: enabled
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-${appVersion}-config-defaults
