apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    # Default values for AMD Device Metrics Exporter.
    # See https://github.com/ROCm/device-metrics-exporter for full options.
    platform: k8s
    monitor:
      resources:
        gpu: true
        nic: false
    image:
      repository: docker.io/rocm/device-metrics-exporter
      tag: v1.4.2
      pullPolicy: Always
    service:
      type: ClusterIP
    serviceMonitor:
      enabled: true
      interval: "30s"
      additionalLabels:
        prometheus.kommander.d2iq.io/select: "true"
