{
 "title": "Platform Apps / Logging Stack Stress",
 "tags": [
  "logging operator",
  "platform apps",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "fluentdplugin",
    "label": "Fluentd Plugin",
    "query": {
     "query": "label_values(fluentd_output_status_emit_records, plugin_id)"
    }
   },
   {
    "name": "fluentbit",
    "query": {
     "query": "label_values(fluentbit_input_bytes_total,pod)"
    }
   },
   {
    "name": "fluentd",
    "query": {
     "query": "label_values(fluentd_output_status_emit_count,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Fluentbit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "1-min Avg Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{pod=~\"logging-operator-logging-fluentbit.*\",container=\"fluent-bit\"}[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Terminated by Error/OOM Killer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"logging-operator-logging-fluentbit.*\",reason=\"OOMKilled\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    },
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"logging-operator-logging-fluentbit.*\",reason=\"Error\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Fluentd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "1-min Avg Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{pod=~\"logging-operator-logging-fluentd-.*\", container=\"fluentd\"}[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Terminated by Error/OOM Killer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{pod=~\"logging-operator-logging-fluentd-[0-9]*\",reason=\"OOMKilled\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    },
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"logging-operator-logging-fluentd-[0-9]*\",reason=\"Error\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "1-min Max fluentd_output_status_buffer_total_bytes in Mbs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_buffer_total_bytes[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "1-min Max fluentd_output_status_retry_wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_retry_wait[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "1-min Max fluentd_output_status_buffer_queue_length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_buffer_queue_length[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Retry count / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(fluentd_output_status_retry_count[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Loki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "1-min Avg Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{pod=~\"grafana-loki-v3-.*\"}[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Terminated by Error/OOM Killer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{pod=~\"grafana-loki-v3-.*\",reason=\"OOMKilled\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    },
    {
     "expr": "kube_pod_container_status_terminated_reason{pod=~\"grafana-loki-v3-.*\",reason=\"Error\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Distributor: 1-min Avg ingester append failure rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_append_failures_total[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Distributor: 1-min bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_bytes_received_total[1m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Ingestor: series pending in the flush queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "cortex_ingester_flush_queue_length",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}