.PHONY: go-test
go-test:
	cd hack/release && go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

.PHONY: mod-tidy
mod-tidy:
	cd hack/release && go mod tidy

.PHONY: go-lint
go-lint:
	cd hack/release && golangci-lint run --fix ./...
	cd hack/release && go fmt ./...
	cd hack/release && go fix ./...
