apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nkp-insights-management
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-${appVersion}
    namespace: ${releaseNamespace}
  dependsOn:
    - name: kubefed
      namespace: ${releaseNamespace}
  install:
    serverSideApply: true
    crds: CreateReplace
    remediation:
      retries: 30
  interval: 15s
  releaseName: nkp-insights-management
  targetNamespace: ${releaseNamespace}
  upgrade:
    serverSideApply: enabled
    crds: CreateReplace
    remediation:
      retries: 30
  rollback:
    serverSideApply: enabled
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-${appVersion}-config-defaults
