apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true

    global:
      priorityClassName: system-cluster-critical
  # Just a workaround for empty kubernetes kustomizations
