{
 "title": "Global Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster (Monitoring ID/clusterId)",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   { "name": "interval", "query": "4h" }
  ]
 },
 "panels": [
  {
   "title": "Attached Clusters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(prometheus_build_info)" }
   ]
  },
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Utilisation",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\"}[1m])) by (cluster)"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"}) by (cluster) / sum(kube_node_status_allocatable{resource=\"cpu\",cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "(sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"}) by (cluster)) / (sum(kube_node_status_allocatable{resource=\"cpu\",cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=~\"$cluster\"}) by (cluster) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"}) by (cluster) / sum(kube_node_status_allocatable{resource=\"memory\",cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"}) by (cluster) / sum(kube_node_status_allocatable{resource=\"memory\",cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_owner{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}) by (workload, namespace)) by (cluster)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) by (cluster) / sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"}) by (cluster)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"\",cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Memory Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Requests by Cluster",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_owner{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}) by (workload, namespace)) by (clustereramespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\", container!=\"\"}) by (cluster)"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\", container!=\"\"}) by (cluster) / sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"}) by (cluster)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\", container!=\"\"}) by (cluster) / sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"}) by (cluster)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Current Network Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\".+\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\".+\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\".+\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\".+\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\".+\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\".+\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster)"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\".+\",cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\".+\",cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }
  },
  {
   "title": "Average Container Bandwidth by Namespace: Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{namespace=~\".+\",cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace: Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{namespace=~\".+\",cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Rate of Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\".+\",cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\".+\",cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Rate of Packets Dropped", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\".+\",cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\".+\",cluster=~\"$cluster\"}[$interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Storage IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(cluster) (rate(container_fs_reads_total{container!=\"\", cluster=~\"$cluster\"}[5m]) + rate(container_fs_writes_total{container!=\"\", cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (rate(container_fs_reads_bytes_total{container!=\"\", cluster=~\"$cluster\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\", cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Storage IO - Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by(cluster) (rate(container_fs_reads_total{container!=\"\", cluster=~\"$cluster\"}[5m]))"
    },
    {
     "expr": "sum by(cluster) (rate(container_fs_writes_total{container!=\"\", cluster=~\"$cluster\"}[5m]))"
    },
    {
     "expr": "sum by(cluster) (rate(container_fs_reads_total{container!=\"\", cluster=~\"$cluster\"}[5m]) + rate(container_fs_writes_total{container!=\"\", cluster=~\"$cluster\"}[5m]))"
    },
    {
     "expr": "sum by(cluster) (rate(container_fs_reads_bytes_total{container!=\"\", cluster=~\"$cluster\"}[5m]))"
    },
    {
     "expr": "sum by(cluster) (rate(container_fs_writes_bytes_total{container!=\"\", cluster=~\"$cluster\"}[5m]))"
    },
    {
     "expr": "sum by(cluster) (rate(container_fs_reads_bytes_total{container!=\"\", cluster=~\"$cluster\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\", cluster=~\"$cluster\"}[5m]))"
    }
   ]
  }
 ]
}