---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kommander-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ./common/kommander-operator/chart
      sourceRef:
        kind: GitRepository
        name: management
        namespace: kommander-flux
  interval: 15s
  install:
    serverSideApply: true
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    serverSideApply: enabled
    crds: CreateReplace
    remediation:
      retries: 30
  rollback:
    serverSideApply: enabled
  valuesFrom:
    - kind: ConfigMap
      name: kommander-operator-values
    - kind: ConfigMap
      name: kommander-operator-overrides
      optional: true
