name: "Pull Request Labeler"
on:
  pull_request:
    branches:
      - main
      - 'release-*'
    paths:
      - 'applications/**/*'
  workflow_dispatch: {}

# https://stackoverflow.com/a/72408109/3058839
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  label-pr:
    runs-on: self-hosted-nutanix-small
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add identifying label to PRs updating applications
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.MESOSPHERECI_USER_TOKEN }}"
          configuration-path: ".github/app-labeler.yaml"
      - name: Add labels to automated chart bump PRs
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.MESOSPHERECI_USER_TOKEN }}"
          configuration-path: ".github/app-pr-labeler.yaml"
