name: Retag and Push Images to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - sandy/retag-valkey # branch updated for testing

jobs:
  push-charts:
    runs-on: 
      - self-hosted-nutanix-docker-small
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag and push images
        run: |
          set -e

          IMAGES=(
            "valkey:8.1.3-debian-12-r2"
            "valkey-sentinel:8.1.3-debian-12-r2"
            "redis-exporter:1.74.0-debian-12-r3"
          )

          for IMAGE in "${IMAGES[@]}"; do
            echo "Processing $IMAGE"

            docker pull bitnamilegacy/$IMAGE
            docker tag bitnamilegacy/$IMAGE ghcr.io/nutanix-cloud-native/$IMAGE
            docker push ghcr.io/nutanix-cloud-native/$IMAGE
            echo "Pushed $IMAGE to ghcr.io/nutanix-cloud-native"
          done
