name: Close Stale PRs

on:
  schedule:
    - cron: "0 15 * * 1-5"
  workflow_dispatch: ~

# https://stackoverflow.com/a/72408109/3058839
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    name: Close Stale PRs
    runs-on: self-hosted-nutanix-small
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          days-before-pr-stale: 30
          days-before-pr-close: 10
